#!/usr/bin/env python3

import gi

gi.require_version('Gtk', '3.0')
from gi.repository import Gtk as gtk
from gi.repository import GObject

from pppoediplugin.PppoeDi import PppoeDi

if __name__ == '__main__':
    pppoe = PppoeDi()
    GObject.threads_init()
    gtk.main()
